apollo:
  meta: http://172.25.20.143:8080
  bootstrap:
    enabled: true
    # will inject 'application' and 'TEST1.apollo' namespaces in bootstrap phase
    namespaces: application.yml,application,suntek.console
spring:
  devtools:
    livereload:
      port: 30980
      enabled: true
  profiles:
    active: prod
server:
  port: 8089
# 数据库授权
#  grant all on *.* to admin@'%' identified by 'suntek';